### PR TITLE
Failing Spec Harness Test to Create New Item

### PR DESCRIPTION
**Pull request by kristastadler**
I've been struggling with this issue since yesterday and was hoping that today's lesson would help, but I'm still having the same issue.

Even though my Rspec tests in my Rails Engine are passing fine, when I run the spec harness, I get a failure: 
```
`2) Spec Harness ReST endpoints Items can create and delete an item
     Failure/Error: expect(new_item[:attributes][:name]).to eq(name)
     
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./spec/features/harness_spec.rb:66:in `block (4 levels) in <top (required)>'
`
```
After looking more closely at the test, I'm failing because I'm not getting a successful response from the API. 

This is my response error: 
```
Completed 500 Internal Server Error in 15ms (ActiveRecord: 4.3ms)

ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "items_pkey"
DETAIL:  Key (id)=(12) already exists.
: INSERT INTO "items" ("name", "description", "unit_price", "created_at", "updated_at", "merchant_id") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"):
```
Any ideas on what I'm doing wrong? I tried to set up my test object params to be exactly the same as what the test is passing through. I've also tried using item_params instead of this new create_params I've added to the controller -- but then I just get a 400-level error that it cannot create the item because it doesn't know what :item is.

### CODE REVIEW

**Comment by kristastadler** [comment]
@BrianZanti, @dionew1

**Comment by BrianZanti** [comment]
I tried setting up your project to take a closer look, but it looks like your `config` folder is being gitignored. I can't run the project without those files.

Looking at your error, it seems odd that it is trying to create an item with id 12. If your database is seeded with all the items, it should be creating a new item with an id in the 2000s. My guess is that you did not reset the primary key sequence when importing your data.

**Comment by kristastadler** [comment]
Thanks Brian, I'll try to research how to reset the primary key sequence! That does seem like an odd id and I didn't pick up on it.

**Comment by kristastadler** [comment]
Resolve issue with primary key sequence.

**Pull request merged**
